on: [pull_request]
name: Check
permissions:
  contents: read
jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04-arm, windows-2025, macos-26]
        go: [1.23.x, 1.24.x, 1.25.x]
    continue-on-error: true
    steps:
      - name: Checkout source
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version: ${{ matrix.go }}
      - name: Lint
        uses: golangci/golangci-lint-action@0a35821d5c230e903fcfe077583637dea1b27b47 # v9
        with:
          version: v2.2.2
      - name: Test
        run: go test -v ./...
